name: LinksuJump
version: '0.0.1'
main: org.example2.Sheepy.LinksuJump
api-version: '1.20'
commands:
  linksu:
    usage: '/linksu reload'
    aliases:
      - linksujump
permissions:
  linksujump.linksu:
    description: use egg and arrow
    default: op