name: LinksuJump
version: '0.0.1'
main: org.example2.Sheepy.LinksuJump
api-version: '1.20'
commands:
  linksu:
    usage: '/linksu <reload/limit>'
    permission: "linksujump.linksu"
    aliases:
      - linksujump

permissions:
  linksujump.projectile:
    description: use egg and arrow
    default: op
  linksujump.linksu:
    description: use command
    default: op
