name: Sheepy
version: '0.0.1'
main: org.example2.Sheepy.Sheepy
api-version: '1.20'
commands:
#  test:
#    description: jea
#    aliases:
#      - t
  s:
    description: stop tasks
#  load:
#    description: load animation from file
#    aliases:
#      - l
  stream:
    description: stream from file
    usage: "/stream <file> [particle scale] [animation scale] [particle type] [particles per tick]"
    aliases:
      - st